AMQP_BROKER_URL = process.env.AMQP_BROKER_URL
AMQP_BROKER_PORT = process.env.AMQP_BROKER_PORT
DOMAIN = process.env.DOMAIN;
SOCKET_URL = process.env.SOCKET_URL;
SOCKET_PORT = process.env.SOCKET_PORT;

exports.AMQP_BROKER_URL = AMQP_BROKER_URL;
exports.AMQP_BROKER_PORT = AMQP_BROKER_PORT;
exports.SOCKET_URL = SOCKET_URL;
exports.SOCKET_PORT = SOCKET_PORT;
exports.DOMAIN = DOMAIN;